stages:
    - build
    - test
    - docker
    - deploy

build_debug:
    stage: build
    before_script:
      - cd majumi.CarService.VisitsDataService.Rest
    script:
      - dotnet build -c Debug
    tags:
      - dotnet

build_release:
    stage: build
    before_script:
      - cd majumi.CarService.VisitsDataService.Rest
    script:
      - dotnet build -c Release
    tags:
      - dotnet

unit_test:
    stage: test
    needs: [build_release, build_debug]
    before_script:
      - cd majumi.CarService.VisitsDataService.Rest.Tests
    script:
      - dotnet test
    tags:
      - dotnet

build_image:
    stage: docker
    needs: [unit_test]
    before_script:
      - cd Docker
    script:
      - ./BuildImage.bat
    tags:
      - docker

push_image:
    stage: docker
    needs: [build_image]
    before_script:
      - cd Docker
    script:
      - ./PushImage.bat
    tags:
      - docker

production:
    stage: deploy
    needs: [push_image]
    script:
      - kubectl config set-cluster microk8s-cluster --server=http://localhost:8080 --insecure-skip-tls-verify
      - kubectl config set-credentials admin --token=$KUBERNETES_TOKEN
      - kubectl config set-context microk8s --cluster=microk8s-cluster --namespace=default --user=admin
      - kubectl config use-context microk8s
      - kubectl rollout restart deployment/visitsdataservice-deploy
    tags:
      - kubernetes